/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App
{
    public static void main(String[] args) throws Exception
    {
        System.setOut(new java.io.PrintStream(
            new java.io.FileOutputStream(java.io.FileDescriptor.out),
            true,
            "UTF-8"
        ));

        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);
        ProductProvider provider = context.getBean(ProductProvider.class);
        Renderer renderer = context.getBean(Renderer.class);
        renderer.render(provider.getProducts());
    }
}